### PR TITLE
Possible fix for #63

### PR DESCRIPTION
**Pull request by HowardBaxton**
See issue #63 for more details.

### CODE REVIEW

**Comment by HowardBaxton** [comment]
This fix is working well.  I'd like to see it merged and if we find more issues, we can create a new branch at that time.

**Comment by LeonaMorro** [comment]
- line 51 seems to be redundant because of line 55
- line 60 seems to be redundant because of line 58
- line 61-76 and line 100-116 are almost the same. Use a function?
- line 109: Why do we need a llSleep?

**Comment by HowardBaxton** [comment]
line 51 seems to be redundant because of line 55

Agreed and fixed.

line 60 seems to be redundant because of line 58

Also agreed and fixed.

line 61-76 and line 100-116 are almost the same. Use a function?

I do not disagree with this but due to the last item below, I'd rather leave this alone for now.  I'd be happy to put this up as a future issue and address both at a later time.

line 109: Why do we need a llSleep?

The llSleep is there for temp attach items.  These items within SATMSG lines will always follow rez object, then give attach command.  Without the pause, temp attach always fails and adding a pause in a SATMSG is not supported.

**Comment by LeonaMorro** [comment]
llSleep:
You stated that we need it but It seems that you removed it (accidenlty?) from this Pull request.
Additional Question: Why is it needed in SATMSGs but not in NOTSATMSGs?

**Comment by LeonaMorro** [comment]
once again ... llSleep:
can you give me an example NC content for the failing tempAttachment?

**Comment by LeonaMorro** [comment]
example NC content:

```
ANIM|Legs Crossed|<-0.8,0,0.8>|<0,0,0>
SATMSG|207|rez prop||1
SATMSG|-6002|Male Create Glasses=attach/17|%AVKEY%|1
NOTSATMSG|-6002|Male Create Glasses=detach/17|%AVKEY%|1

ANIM|Legs Crossed|<0.8,0,0.8>|<0,0,180>
SATMSG|207|rez prop 1||2
SATMSG|-6002|Male Create Glasses 1=attach/17|%AVKEY%|2
NOTSATMSG|-6002|Male Create Glasses 1=detach/17|%AVKEY%|2
```

Explanation:
1) line 2: a DOACTION is send. The NC Reader will response with a DOACTION_READER AFTER the card is fully read.
2) a LinkMessage is send via chatchannel 1.5s after the card reading is initialisized. If reading the card and rezzing the prop lasts longer than 1.5s this will fail. Reading one line (uncached) lasts min. 0.1s. So if the card is longer than 15 lines, this will fail.

Conclusion:
- a simple llSleep() don't cover all cases
- mixing DOACTIONS (asynchron) and LINKMSG (synchron) isn't a nice idea if the order of the resulting messages is important

Questions
1) Why don't write the attach/detach messages into the corresponding NC?
2) What is the meaning of: `||1` in `SATMSG|207|rez prop||1` and `||2`in `SATMSG|207|rez prop 1||2`? I don't see any code that makes use of it ...

**Comment by HowardBaxton** [comment]
Tried your 1. And it fails.
The meaning of ||1is for SATMSG to be associated with seat1, the optional
way to associate but not optional with SCHMO(E).

**Comment by LeonaMorro** [comment]
Did you use the pause command?

||1: OMG ... sometimes I'm really stupid ....

**Comment by HowardBaxton** [comment]
Lol..not stupid.  I did try the PAUSE|1.5 in the red prop NC

**Pull request merged**
