### PR TITLE
Leona example for #39 recommendations 1

### PR DESCRIPTION
**Pull request by HowardBaxton**
I cannot find issue now with this branch.

To be sure, the core required a change as well as the menu.

To be honest the core was wrong in how it processed LINKMSG lines, this new change makes perfect sense and I actually thought it was working as it is after the change (evil slight of hand got in there).

### CODE REVIEW

**Comment by HowardBaxton** [comment]
I see a comment in the menu script that the global permissions could be removed and use root menu button permissions instead.  This might be a major change as it would require existing builds to be modified to work the same way.  My thoughts are to leave the global in and perhaps remove them in a V2.  We should discuss more as I may just have blinders on again.

**Comment by LeonaMorro** [comment]
No blinders. The intension was to show that the menu permission could be removed without loosing any functionality. But of course it could not be removed because of the existing builds.

**Comment by LeonaMorro** [comment]
@HowardBaxton: can you add the new adjuster code (with the updated timer) also?

**Comment by LeonaMorro** [comment]
I fixed the Adjuster sanity check (see last commit). And I have some questions:
1.)
What is the difference between the 2 linkMessages:
ADJUST (201) and REZ_ADJUSTERS (2) 

```
        else if(num == ADJUST) { //adjust has been chosen from the menu
            llSay(chatchannel, "adjuster_die");
            adjusters = [];
            RezAllAdjusters();
        }
...
        else if (num == REZ_ADJUSTERS && str == "RezAdjuster"){    //got a new pose so update adjusters.
            adjusters = [];
            RezAllAdjusters();
        }
```

2)
Now you are rezzing all Adjusters very fast in a loop. After they are rezzed, they generate a `object_rez` event where you add their UUIDs to a list. I guess that the order of the lists represent the order of the seats they belong to. Question: is it sure that the events are generated in the same order as the Adjusters are rezzed? Or is the event generated AFTER each Adjuster is rezzed (which can vary because of some lag on the simulator)? Wouldn't it be smarter to let the Adjusters knwo to which seat they belong and let them use the seat# in every message they send?

**Comment by HowardBaxton** [comment]
The two commands to do adjusters come from two different scenarios within the script:
Adjust comes from the menu click to start the Adjusters.
REZ_ADJUSTERS comes from the core when there is a pose change and Adjusters are already in play.

I think your sanity change will do no harm but it does change the function of the REZ_ADJUSTERS so should be watched a bit.

Yes I do agree there is some slight magic going on to always have the Adjuster keys in the correct order (I've been watching this for years with no mistakes).  I also agree it would be nice to assign the correct seat# to match the Adjuster key in the adjusters list but we can only pass one integer in the rezobject function so it becomes difficult to send chatchannel and seat#.  It is possible to have the Adjuster do some hand shake and report it's position, then have the core sort out which seat for the list but seems extra code to fix something that I've never seen fail yet. (doesn't mean it won't fail sometime tho)  

llRezObject does fire the Object_Rez event within the same script to grab the Adjuster key so we not waiting on the adjuster to rez just to get it's key.  This is probably a safe bet the order is maintained.  If history would have revealed a problem here, I'd have changed how this was handled because I've always watched this one.

I noticed last night there is another anomaly that requires looking into with more importance than the above:  When Adjusters are rezzed and selecting the same pose from the menu, SAT and NOTSATMSG's are run (not just once but twice).  This doesn't happen when Adjusters are not rezzed (all functions as intended).  I have not verified this on older versions but I am certain it will also be seen there.  The SAT_NOTSAT handler would need to know if adjusters are in play and not react in this situation and currently there is no means for the 'handler' to get this info.

**Comment by LeonaMorro** [comment]
last commit: implemented a way to let the Adjuster know its "slotnumber".
Therefore the number of possible chatchannels is reduced from 4,294,967,296 to 16,777,216
The maximal number of slots handled this way is 256

**Comment by LeonaMorro** [comment]
ADJUST (201) and REZ_ADJUSTERS (2):
Well .. i see the both scenarios, but I don't see a difference in the handling:

## REZ_ADJUSTERS (2)

### Core:

```
  if(rezadjusters) {
    llRegionSay(chatchannel, "adjuster_die");
    llMessageLinked(LINK_SET, REZ_ADJUSTERS, "RezAdjuster", "");
  }
```

### Slave:

```
  else if (num == REZ_ADJUSTERS && str == "RezAdjuster"){    //got a new pose so update adjusters.
    adjusters = [];
    RezAllAdjusters();
  }
```

### Result:

adjusters die and get rezzed again

## ADJUST (201)

### Menu:

```
  else if(selection == ADJUSTBTN) {
    llMessageLinked(LINK_SET, ADJUST, "", "");
    AdminMenu(toucherid, path, "", adminbuttons);
  }
```

### Core:

```
  else if(num == ADJUST) { 
    rezadjusters = TRUE;
  }
```

### Slave:

```
  else if(num == ADJUST) { //adjust has been chosen from the menu
    llSay(chatchannel, "adjuster_die");
    adjusters = [];
    RezAllAdjusters();
  }
```

### Result:

adjusters die and get rezzed again

**Comment by LeonaMorro** [comment]
You wrote:
"Yes I do agree there is some slight magic going on to always have the Adjuster keys in the correct order (I've been watching this for years with no mistakes)"

You currently changed the way the Adjusteres are rezzed in the commit 7a3382a022a5147c07552d3688454c9a619d52bc

Before this commit the Adjusters were rezzed sequential. After the commit they are rezzed in a bunch.

**Comment by LeonaMorro** [comment]
we split this branch to smaler branches

**Pull request closed without merging**
